"""Generate JSON Schema (as YAML) artifacts from the Pydantic contract models.

Run this after installing the dependencies:

    pip install "pydantic>=2" pyyaml
    python contract/generate_schemas.py

This script self-bootstraps sys.path, so it does not need the package to be
installed. (Once a build backend is chosen for the repo, an editable install with
"pip install -e ." becomes an alternative, but there is no backend yet, so the
two-package install above is the supported path.)

This is the ONLY writer of contract/schemas/. The YAML files it produces are
generated artifacts: do not hand-edit them. They are committed and checked for
staleness in CI, so the output must be deterministic. Determinism here relies on
a pinned pydantic (see pyproject.toml), a fixed pyyaml dump configuration, and a
trailing newline on every file.

$defs note: each operation file is generated independently, so shared component
schemas (ProfileStep, Error, the enums, and so on) are inlined under $defs in
every file that references them, and are also written to their own files under
schemas/components/. This duplication is accepted for now: each operation file is
self-contained and independently valid. Emitting a shared $defs with cross-file
$ref (pydantic's default ref_template is intra-file only) is a noted later
refinement.
"""

from __future__ import annotations

import os
import sys

# Bootstrap the import path so `mightex_contract` resolves when this script is
# run directly as `python contract/generate_schemas.py`.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pathlib import Path  # noqa: E402
from typing import Any  # noqa: E402

import yaml  # noqa: E402
from pydantic import TypeAdapter  # noqa: E402

from mightex_contract import (  # noqa: E402
    ChannelState,
    ControllerCapabilities,
    DeviceDescriptor,
    DeviceInfo,
    Error,
    ErrorType,
    ModuleType,
    NormalParameters,
    OperatingMode,
    ProfileStep,
    StrobeParameters,
    TriggerParameters,
    TriggerPolarity,
)
from mightex_contract import operations as ops  # noqa: E402

HEADER = (
    "# Generated by contract/generate_schemas.py. Do not edit.\n"
    "# Source of truth: the Pydantic models in contract/mightex_contract/.\n"
)

SCHEMAS_DIR = Path(__file__).resolve().parent / "schemas"


def _model_schema(model: Any) -> dict:
    """JSON Schema for a Pydantic BaseModel subclass."""
    return model.model_json_schema()


def _adapter_schema(tp: Any) -> dict:
    """JSON Schema for a type that is not a BaseModel (union, alias, or enum)."""
    return TypeAdapter(tp).json_schema()


# PyYAML can only encode an embedded newline in a quoted scalar via a blank
# physical line, so docstring paragraph breaks would dump as blank lines.
def _normalize_descriptions(obj: Any) -> Any:
    """Recursively collapse "description" string values to single-line text."""
    if isinstance(obj, dict):
        normalized = {}
        for key, value in obj.items():
            if key == "description" and isinstance(value, str):
                normalized[key] = " ".join(value.split())
            else:
                normalized[key] = _normalize_descriptions(value)
        return normalized
    if isinstance(obj, list):
        return [_normalize_descriptions(item) for item in obj]
    return obj


def _dump(path: Path, payload: dict) -> None:
    """Write payload as YAML with the generated header and a trailing newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        _normalize_descriptions(payload),
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    if not body.endswith("\n"):
        body += "\n"
    path.write_text(HEADER + body)


# The 18 operations, each mapped to (request model, reply union). The names are
# the public operation names and become the operation file stems.
OPERATIONS: dict[str, tuple[Any, Any]] = {
    "enumerate_devices": (ops.EnumerateDevicesRequest, ops.EnumerateDevicesReply),
    "open_device": (ops.OpenDeviceRequest, ops.OpenDeviceReply),
    "get_capabilities": (ops.GetCapabilitiesRequest, ops.GetCapabilitiesReply),
    "device_info": (ops.DeviceInfoRequest, ops.DeviceInfoReply),
    "initialize": (ops.InitializeRequest, ops.InitializeReply),
    "store_settings": (ops.StoreSettingsRequest, ops.StoreSettingsReply),
    "restore_factory_defaults": (ops.RestoreFactoryDefaultsRequest, ops.RestoreFactoryDefaultsReply),
    "soft_reset": (ops.SoftResetRequest, ops.SoftResetReply),
    "set_fan_pwm_level": (ops.SetFanPwmLevelRequest, ops.SetFanPwmLevelReply),
    "close_device": (ops.CloseDeviceRequest, ops.CloseDeviceReply),
    "configure_normal": (ops.ConfigureNormalRequest, ops.ConfigureNormalReply),
    "set_normal_current": (ops.SetNormalCurrentRequest, ops.SetNormalCurrentReply),
    "configure_strobe": (ops.ConfigureStrobeRequest, ops.ConfigureStrobeReply),
    "configure_trigger": (ops.ConfigureTriggerRequest, ops.ConfigureTriggerReply),
    "set_active_mode": (ops.SetActiveModeRequest, ops.SetActiveModeReply),
    "get_active_mode": (ops.GetActiveModeRequest, ops.GetActiveModeReply),
    "read_parameters": (ops.ReadParametersRequest, ops.ReadParametersReply),
    "read_load_voltage": (ops.ReadLoadVoltageRequest, ops.ReadLoadVoltageReply),
}

# Component files, one generated schema per file, mirroring the one-file-per-operation
# convention. Each stem maps to the single schema it owns and the stem is the file name
# (e.g. normal_parameters -> components/normal_parameters.yaml).
#
# One-schema-per-file is an intentional reversal of the earlier "one cohesive concept
# per file" grouping: profile (ProfileStep + Profile) and the error concept (Error +
# ErrorType) used to share a file. We chose artifact uniformity over concept grouping so
# every component file is single-schema, which also regularizes the name -> file-stem
# mapping a later cross-file $ref refactor depends on. Deliberate invariant change, not drift.
#   - The error concept is likewise split in the Python module layer: error.py (Error) and
#     error_type.py (ErrorType), mirroring the error.yaml and error_type.yaml artifacts.
#   - Profile (the Annotated[list[ProfileStep], max_length=127] alias in profile.py) is
#     intentionally a Python-only convenience alias used in API signatures. It is
#     deliberately NOT exported as a generated schema; only ProfileStep emits.
#
# Root-shape note: each file keeps a top-level {SchemaName: schema} mapping, so a single-
# schema concept still nests under its schema-name key. Collapsing that now redundant
# wrapper key is a deferred refinement, intentionally left out here so the generated
# component root shape stays unchanged by this split.
COMPONENTS: dict[str, dict[str, Any]] = {
    "normal_parameters": {"NormalParameters": NormalParameters},
    "strobe_parameters": {"StrobeParameters": StrobeParameters},
    "trigger_parameters": {"TriggerParameters": TriggerParameters},
    "channel_state": {"ChannelState": ChannelState},
    "device_info": {"DeviceInfo": DeviceInfo},
    "device_descriptor": {"DeviceDescriptor": DeviceDescriptor},
    "controller_capabilities": {"ControllerCapabilities": ControllerCapabilities},
    "operating_mode": {"OperatingMode": OperatingMode},
    "trigger_polarity": {"TriggerPolarity": TriggerPolarity},
    "module_type": {"ModuleType": ModuleType},
    "profile_step": {"ProfileStep": ProfileStep},
    "error": {"Error": Error},
    "error_type": {"ErrorType": ErrorType},
}


def _schema_for(obj: Any) -> dict:
    """Pick the right schema export for a model, union, alias, or enum."""
    if isinstance(obj, type) and hasattr(obj, "model_json_schema"):
        return _model_schema(obj)
    return _adapter_schema(obj)


def generate_components() -> dict[str, str]:
    """Write one file per component concept; return a name -> file index."""
    components_dir = SCHEMAS_DIR / "components"
    index: dict[str, str] = {}
    for concept, members in COMPONENTS.items():
        _dump(
            components_dir / f"{concept}.yaml",
            {name: _schema_for(obj) for name, obj in members.items()},
        )
        index[concept] = f"components/{concept}.yaml"
    return index


def generate_operations() -> dict[str, Any]:
    """Write one self-contained file per operation; return an operation index."""
    operations_dir = SCHEMAS_DIR / "operations"
    index: dict[str, Any] = {}
    for name, (request, reply) in OPERATIONS.items():
        _dump(
            operations_dir / f"{name}.yaml",
            {
                "operation": name,
                "request": _model_schema(request),
                "reply": _adapter_schema(reply),
            },
        )
        index[name] = {
            "request": f"operations/{name}.yaml#/request",
            "reply": f"operations/{name}.yaml#/reply",
        }
    return index


def generate_index(
    operation_index: dict[str, Any], component_index: dict[str, str]
) -> None:
    """Write the top-level operations.yaml index over operations and components."""
    _dump(
        SCHEMAS_DIR / "operations.yaml",
        {"operations": operation_index, "components": component_index},
    )


def main() -> None:
    component_index = generate_components()
    operation_index = generate_operations()
    generate_index(operation_index, component_index)
    print(f"Wrote schema artifacts under {SCHEMAS_DIR}")


if __name__ == "__main__":
    main()
