# ------------------------------------------------------------------------------
#  Filename: generate_schemas.py
#
#  Purpose: Generate deterministic YAML schema artifacts from the Pydantic contract.
#
#  Copyright (C) 2026 Logan Kaising.  All rights reserved.
# ------------------------------------------------------------------------------

"""Generate the slice's JSON Schema (as YAML) artifacts into schemas/.

Run from the repo root:

    python scripts/generate_schemas.py

This script is the only writer of schemas/; the YAML files it produces are
generated artifacts and must never be hand-edited. It bootstraps sys.path to
src/, so it works with or without the package installed.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml
from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from mightex_slc.contract import (  # noqa: E402
    CloseDeviceReply,
    CloseDeviceRequest,
    ConfigureNormalReply,
    ConfigureNormalRequest,
    ControllerCapabilities,
    DeviceDescriptor,
    EnumerateDevicesReply,
    EnumerateDevicesRequest,
    Error,
    ErrorType,
    InitializeReply,
    InitializeRequest,
    ModuleType,
    OpenDeviceReply,
    OpenDeviceRequest,
    OperatingMode,
    SetActiveModeReply,
    SetActiveModeRequest,
)

SCHEMAS_DIR = REPO_ROOT / "schemas"

HEADER = (
    "# Generated by scripts/generate_schemas.py. Do not edit.\n"
    "# Source of truth: the Pydantic models in src/mightex_slc/contract/.\n"
)

OPERATIONS: dict[str, tuple[Any, Any]] = {
    "enumerate_devices": (EnumerateDevicesRequest, EnumerateDevicesReply),
    "open_device": (OpenDeviceRequest, OpenDeviceReply),
    "initialize": (InitializeRequest, InitializeReply),
    "configure_normal": (ConfigureNormalRequest, ConfigureNormalReply),
    "set_active_mode": (SetActiveModeRequest, SetActiveModeReply),
    "close_device": (CloseDeviceRequest, CloseDeviceReply),
}

COMPONENTS: dict[str, Any] = {
    "controller_capabilities": ControllerCapabilities,
    "device_descriptor": DeviceDescriptor,
    "error": Error,
    "error_type": ErrorType,
    "module_type": ModuleType,
    "operating_mode": OperatingMode,
}


class _NoFieldTitles(GenerateJsonSchema):
    """Suppress mechanical field titles; keep model/enum schema-level titles."""

    def field_title_should_be_set(self, schema) -> bool:
        return False


def _schema(tp: Any) -> dict:
    return TypeAdapter(tp).json_schema(schema_generator=_NoFieldTitles)


def _one_line_descriptions(obj: Any) -> Any:
    """Collapse description values to single-line text for stable YAML output."""
    if isinstance(obj, dict):
        return {
            key: " ".join(value.split())
            if key == "description" and isinstance(value, str)
            else _one_line_descriptions(value)
            for key, value in obj.items()
        }
    if isinstance(obj, list):
        return [_one_line_descriptions(item) for item in obj]
    return obj


def _write(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        _one_line_descriptions(payload),
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    path.write_text(HEADER + body)


def main() -> None:
    for name, component in COMPONENTS.items():
        _write(SCHEMAS_DIR / "components" / f"{name}.yaml", _schema(component))
    for name, (request, reply) in OPERATIONS.items():
        _write(
            SCHEMAS_DIR / "operations" / f"{name}.yaml",
            {"operation": name, "request": _schema(request), "reply": _schema(reply)},
        )
    print(f"Wrote {len(COMPONENTS) + len(OPERATIONS)} schema files under {SCHEMAS_DIR}")


if __name__ == "__main__":
    main()
